//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalYearProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinalYearProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to palavos.
        /// </summary>
        internal static string ENGL_A_diet_for_Better_Energy {
            get {
                return ResourceManager.GetString("ENGL_A_diet_for_Better_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to palavos.
        /// </summary>
        internal static string ENGL_How_Nuclear_Power_Can_Stop_Global_Warming {
            get {
                return ResourceManager.GetString("ENGL_How_Nuclear_Power_Can_Stop_Global_Warming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to palavos.
        /// </summary>
        internal static string ENGL_How_social_networks_can_destroy_your_social_life {
            get {
                return ResourceManager.GetString("ENGL_How_social_networks_can_destroy_your_social_life", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to palavos.
        /// </summary>
        internal static string ENGL_Rocket_Science {
            get {
                return ResourceManager.GetString("ENGL_Rocket_Science", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to palavos.
        /// </summary>
        internal static string ENGL_Tank_Military_Vehicle {
            get {
                return ResourceManager.GetString("ENGL_Tank_Military_Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment le futur de l&apos;intelligence artificielle pourrait révolutionner le monde d&apos;ici 25 ans
        ///
        ///FUTUR - Imaginez la scène: une poignée de scientifiques de renom, réunis dans les locaux de Google, discutant tranquillement de la fin possible de l&apos;histoire humaine d&apos;ici moins d&apos;un siècle. Si ce décor vous semble tout droit sorti d&apos;un roman d&apos;anticipation un rien complotiste, vous allez être surpris.
        ///Car cette rencontre a bien eu lieu, cet été lors de la SciFoo, une série de conférences annuelles données à Mou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FR_Comment_le_futur_de_l {
            get {
                return ResourceManager.GetString("FR_Comment_le_futur_de_l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FR_énergie_nucléaire {
            get {
                return ResourceManager.GetString("FR_énergie_nucléaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Aucune cigarette n’est innocente&quot;, cet adage a notamment été vérifié en 2005 par une étude norvégienne effectuée auprès de 43000 personnes sur une durée de près de 30 ans.
        ///
        ///Les chercheurs ont, en effet, constaté que les personnes fumant de 1 à 4 cigarettes par jour (&quot;petits fumeurs&quot;) ont un taux de mortalité 1,5 fois plus élevé, toutes causes confondues, que les non-fumeurs. Plus particulièrement, si l’on s’en tient à la mortalité causée par les maladies fortement liées à la consommation de tabac, on con [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FR_FUMEUR {
            get {
                return ResourceManager.GetString("FR_FUMEUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un programme informatique est-il capable, à la manière d’un enfant, d’apprendre de son environnement ? S’il reste encore du chemin à parcourir, le machine learning, ou « apprentissage automatique », a connu des avancées significatives ces dernières années, poussé notamment par de grandes entreprises aux moyens inédits. Avec comme icône médiatique le Google Brain, qui a réussi la prouesse, en 2012, de découvrir le concept de chat en analysant des millions d’images issues du Web.
        ///Nourrir le programme : un tr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FR_intelligence_artificielle {
            get {
                return ResourceManager.GetString("FR_intelligence_artificielle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu&apos;est-ce que l&apos;énergie nucléaire ?
        ///
        ///L&apos;énergie nucléaire est l&apos;énergie qui se trouve dans le noyau d&apos;un atome. Les atomes sont les plus petites particules dans lesquelles peut se diviser un matériau. Dans le noyau de chaque atome, il existe deux types de particules (neutrons et protons) qui sont toujours unies. L’énergie nucléaire, c’est l’énergie qui permet l’union permanente des neutrons et des protons.
        ///
        ///L&apos;énergie nucléaire peut être utilisée pour produire de l&apos;électricité. Tout d’abord, l’énergie doi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FR_régime_équilibré {
            get {
                return ResourceManager.GetString("FR_régime_équilibré", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El molino se considera la primera fábrica de la historia, ya que tiene los mismos elementos: un edificio, una fuente de energía, la maquinaria y los operadores, teniendo como resultado la salida de un producto.
        ///
        ///El uso original del molino de viento era el molido de cereales, especialmente el del trigo. Con el tiempo se diversificaron las maneras de aprovechar el viento por medio del mismo mecanismo y se denominó molino de viento a todo aparato movido por la fuerza del viento, sin importar su tarea.
        ///
        ///Mec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SP_funciona_un_molino_de_viento {
            get {
                return ResourceManager.GetString("SP_funciona_un_molino_de_viento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoja de Información Sobre el Plomo
        ///
        ///Plomo
        ///
        ///El Plomo es un elemento que se encuentra comúnmente en el medio ambiente en muchas fuentes diferentes. Este puede representar un riesgo significativo para la salud si ingresa al cuerpo en grandes cantidades. El riesgo es especialmente alto para las mujeres embarazadas y para los niños pequeños. En años recientes la atención de los medios se enfocó sobre los peligros potenciales del plomo en los niños dentro y alrededor de la casa. Sin embargo, el envenenamiento [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SP_Hoja_de_Información_Sobre_el_Plomo {
            get {
                return ResourceManager.GetString("SP_Hoja_de_Información_Sobre_el_Plomo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En el mismo ecuador del año 1988 se empieza a fraguar por las calles del madrileño barrio de Begoña lo que llegará a ser una de las bandas internacionales más importantes del Heavy Metal. Jesús María Hernández Gil, artísticamente bautizado como Txus di Fellatio, comienza a armar la primera formación de Mägo de Oz hasta 1995 al mismo tiempo que milita en las filas del Real Madrid. Aunque su primera vocación estaba inicialmente sobre el campo de fútbol formando parte del primer equipo, su pasión por la música [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SP_Mago_de_Oz_biografia {
            get {
                return ResourceManager.GetString("SP_Mago_de_Oz_biografia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Café es después del petróleo el producto que mas se exporta a nivel mundial. Millones de personas dependen de el, así como muchos paises lo tienen como su principal fuente de riqueza. En algunos paises en desarrollo llega a contabilizar hasta el 50% de sus ingresos económicos. Siendo así y para ser un producto de calidad, el café requiere de una serie de procesos cada vez mas especializados.
        ///
        ///EL CULTIVO
        ///Cafeto en desarrollo
        ///
        ///El cultivo del café se da como en una región de la Tierra denominada Cintur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SP_PROCESO_DE_PRODUCCIÓN_DEL_CAFÉ {
            get {
                return ResourceManager.GetString("SP_PROCESO_DE_PRODUCCIÓN_DEL_CAFÉ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La sociedad del conocimiento, la información y el aprendizaje permanente obligan a plantear estrategias novedosas y creativas en el aula, que estén a la altura de las circunstancias actuales y apunten a formar estudiantes competitivos para un entorno global. Por ello, la preparación cognitiva del docente que decide el uso de TIC, incluye un momento de apropiación personal -uso básico- y otro de apropiación profesional -uso pedagógico-, a través de los cuales se potencia el desarrollo de competencias comunic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SP_Tecnología_que_mejora_la_calidad_de_vida {
            get {
                return ResourceManager.GetString("SP_Tecnología_que_mejora_la_calidad_de_vida", resourceCulture);
            }
        }
    }
}
